version: '3.3'

services: 
  web:
    image: microsoft/multicontainerwordpress
    volumes: 
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot:/var/www/html
    ports: 
      - 8080:80
    restart: always

  redis:
    image: redis:3-alpine
    restart: always